### ISSUE TITLE
infinite loop of xhr calls in background

### ISSUE THREAD

**Issue by krishnasingh1818** [featureflow/featureflow-angular#1]
![45846579-c862f680-bced-11e8-87ae-88df10fe14b5](https://user-images.githubusercontent.com/90309/45850475-a7e07e00-bd79-11e8-9de8-3ba7bf1f7303.png)

**Comment by krishnasingh1818** [comment]
when i run this sample angular app then in developer tools in see infinite loop of continous requests being made.
i have node v8.11.4
angular cli : 1.4.10

**Comment by oliveroldfield** [comment]
Hmm this shouldn't happen of course! The guys are having a look now. Have you tried the standard JS library? We will get back to you asap

**Comment by oliveroldfield** [comment]
One quick note while the team look into it is that you should use the client key in the front end - the one starting 'js-env-'

**Comment by oliveroldfield** [comment]
This was due to an inline method call on the template, the guys have made a fix to the example application. They are updating further throughout the day to demonstrated two other scenarios - live update and local performance caching.
