### ISSUE TITLE
angular.json not found

### ISSUE THREAD

**Issue by krishnasingh1818** [featureflow/featureflow-angular#6]
after getting latest commit and running it locally it gives angular.json not found +

npm install has few warnings.
npm WARN tsickle@0.33.0 requires a peer of typescript@git://github.com/mprobst/TypeScript.git#5456479a4a but none is installed. You must install peer dependencies yourself.
npm WARN featureflow-angular@0.0.0 No repository field.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.4 (node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.4: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})

**Comment by oliveroldfield** [comment]
please try now.

**Comment by oliveroldfield** [comment]
apologies this was in-flight from A6 upgrade, package.json and angular.json updated, v1.2.0 has been published to npm

**Comment by oliveroldfield** [comment]
apologies this was in-flight from A6 upgrade, package.json and angular.json updated,
